//------------------------------------------------------------------------
// Copyright(c) 2026 marinedalek.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename "PEU-1.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"PEU/1 VST3 (64Bit)"
#else
#define stringFileDescription	"PEU/1 VST3"
#endif
#define stringCompanyName		"marinedalek\0"
#define stringLegalCopyright	"Copyright(c) 2026 marinedalek."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
